---
http_interactions:
- request:
    method: get
    uri: https://api.yotpo.com/features/11/get_multiple_owners_settings?owner_ids%5B%5D=300&utoken=Ufo5XkKXNsuh0k9ZMPndRv4DlV9324ptg730KKqC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Yotpo-Api-Connector:
      - Ruby0.1.0
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      Server:
      - nginx/1.7.7
      Date:
      - Mon, 21 Dec 2015 15:56:08 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '557'
      Connection:
      - keep-alive
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"56b166d636c4f6f81a409f9495268ebc"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a0ce1a38df6b3d5b0b6df0276786c085
      X-Runtime:
      - '1.352584'
      P3p:
      - policyref="/w3c/p3p.xml", CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi
        CONi HIS OUR IND CNT", CP="CAO PSA OUR"
      Access-Control-Allow-Credentials:
      - 'true'
    body:
      encoding: UTF-8
      string: '{"status":{"code":200,"message":"OK"},"response":{"300":{"widget_size":{"unit":"percentage","value":100},"font_size":"14","font_type":"Open
        Sans","background_color":{"transparent":true,"color":"#ffffff"},"color_primary":"#3085c7","color_d1":"#26649f","color_d2":"#1d5077","color_l1":"#599dd2","color_l2":"#83b6dd","color_l3":"#accee9","color_l4":"#d6e7f4","color_stars":"#ffd200","color_text_white":"#ffffff","theme":"light","color_text_gray_light":"#e3e3e3","color_text_gray":"#a2a2a2","color_text_gray_dark":"#737373","color_text_gray_darker":"#4f4f4f"}}}'
    http_version: 
  recorded_at: Mon, 21 Dec 2015 15:56:08 GMT
recorded_with: VCR 2.9.3
