---
http_interactions:
- request:
    method: put
    uri: https://api.yotpo.com/features/11/7/admin_mass_update
    body:
      encoding: UTF-8
      string: '{"utoken":"Ufo5XkKXNsuh0k9ZMPndRv4DlV9324ptg730KKqC","settings":{"font_size":"12"}}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Yotpo-Api-Connector:
      - Ruby0.1.0
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      Server:
      - nginx/1.9.4
      Date:
      - Sun, 20 Dec 2015 09:16:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '38'
      Connection:
      - keep-alive
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"a873ac57132fed9ae7f368e3c8c85724"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 287249ae0bb8e752067c2782d0253198
      X-Runtime:
      - '4.872587'
      Access-Control-Allow-Credentials:
      - 'true'
    body:
      encoding: UTF-8
      string: '{"status":{"code":200,"message":"OK"}}'
    http_version: 
  recorded_at: Sun, 20 Dec 2015 09:16:28 GMT
recorded_with: VCR 3.0.0
