---
http_interactions:
- request:
    method: post
    uri: https://api.yotpo.com/v1/apps/LjRHHPuW4zmcLNyLRAlvEkmGqZ1LULYF62FMIzvM/products_name_by_sku/
    body:
      encoding: UTF-8
      string: '{"utoken":"qMwb2i9iJANf7BtXA0MqhKB9opq2sRLRwNYmXaCK","domain_keys":["10"]}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Yotpo-Api-Connector:
      - Ruby1.0.5
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.8.1
      Date:
      - Thu, 13 Dec 2018 13:35:39 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Yotpo-Parsed-Request:
      - '{"format":"json","controller":"products_apps","action":"products_name_by_sku","app_key":"LjRHHPuW4zmcLNyLRAlvEkmGqZ1LULYF62FMIzvM"}'
      Etag:
      - W/"7c20c01de38067e7323a6bb04c1be2fd"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 36483f67-4c6d-4afa-a088-e708358cb331
      X-Runtime:
      - '0.636673'
      Access-Control-Allow-Credentials:
      - 'true'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"status":{"code":200,"message":"ok"},"products":[]}'
    http_version: 
  recorded_at: Thu, 13 Dec 2018 13:35:39 GMT
recorded_with: VCR 2.9.3
