---
http_interactions:
- request:
    method: put
    uri: https://api.yotpo.com/apps/3ovRYNIb6OIAI0ddS7EfpYkHpi0oTKl6bj82Vjiy/features/11/feature_settings/38
    body:
      encoding: UTF-8
      string: '{"utoken":"Ufo5XkKXNsuh0k9ZMPndRv4DlV9324ptg730KKqC","value":10,"key":"font_size"}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Yotpo-Api-Connector:
      - Ruby0.1.0
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      Server:
      - nginx/1.9.4
      Date:
      - Sun, 20 Dec 2015 07:53:36 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '38'
      Connection:
      - keep-alive
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"a873ac57132fed9ae7f368e3c8c85724"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 4dc487a01a6593a0a5816bad35007f86
      X-Runtime:
      - '2.985577'
      Access-Control-Allow-Credentials:
      - 'true'
    body:
      encoding: UTF-8
      string: '{"status":{"code":200,"message":"OK"}}'
    http_version: 
  recorded_at: Sun, 20 Dec 2015 07:53:36 GMT
recorded_with: VCR 3.0.0
